version: "2"
services:
  tf2:
    image: team-brh/tf2:latest
    dns:
      - 172.28.0.2
    networks:
      - game-network
    depends_on:
      - dns
      - cache
    volumes:
      - console:/console
    environment: 
      - CONTAINER_NAME=tf2

  css:
    image: team-brh/css:latest
    dns:
      - 172.28.0.2
    networks:
      - game-network
    depends_on:
      - dns
      - cache
    volumes:
      - fast_download:/fastdownload:ro
      - console:/console
    environment: 
      - CONTAINER_NAME=css

  pz:
    image: team-brh/pz:latest
    dns:
      - 172.28.0.2
    networks:
      - game-network
    depends_on:
      - dns
      - cache
    volumes:
      - pz_db:/home/steam/Zomboid/db
      - pz_save:/home/steam/Zomboid/Saves
      - console:/console
    environment: 
      - CONTAINER_NAME=pz

  l4d2:
    image: team-brh/l4d2:latest
    networks:
      - game-network    
    dns:
      - 172.28.0.2
    depends_on:
      - dns
      - cache
    volumes:
      - fast_download:/fastdownload:ro
      - console:/console
    environment: 
      - CONTAINER_NAME=l4d2
  
  valheim:
    image: team-brh/valheim:latest
    dns:
      - 172.28.0.2
    networks:
      - game-network
    depends_on:
      - dns
      - cache
    volumes:
      - console:/console
      - valheim_save:/valheim_save/worlds
    environment: 
      - CONTAINER_NAME=valheim
  
  factorio:
    image: team-brh/factorio:latest
    ports:
     - "34197:34197/udp"
    volumes:
     - factorio_save:/factorio/saves
     - factorio_mod:/factorio/mods

  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    stop_grace_period: 30s # Set to however long you are willing to wait for the container to gracefully stop
    env_file:
        -  ./containers/palworld/.env
    volumes:
        - palworld:/palworld/
    dns:
      - 172.28.0.2
    networks:
      - game-network
    depends_on:
      - dns
      - cache
  
  cache:
    image: lancachenet/monolithic
    volumes:
      - cache:/data/cache/
    networks:
      game-network:
        ipv4_address: 172.28.0.1
    depends_on:
      - dns

  dns:
    image: lancachenet/lancache-dns
    environment:
      - USE_GENERIC_CACHE=true
      - LANCACHE_IP=172.28.0.1
    networks:
      game-network:
        ipv4_address: 172.28.0.2

  fastdownload:
    image: nginx:1
    volumes:
      - ./containers/fastdownload/default.conf:/etc/nginx/conf.d/default.conf:ro
      - fast_download:/fastdownload:ro

volumes:
  cache:
  pz_db:
  pz_save:
  fast_download:
  console:
  valheim_save:
  factorio_save:
  factorio_mod:
  palworld:

networks:
  game-network:
    ipam:
      config:
      - subnet: 172.28.0.0/16
        ip_range: 172.28.5.0/24
