version: "2"
services:
  tf2:
    ports:
      - "69.162.82.210:27015:27015/udp"
    networks:
      - tf2-network
      - game-network

  css:
    ports:
      - "69.162.82.211:27015:27015/udp"
    networks:
      - css-network
      - game-network

  pz:
    ports:
      - "69.162.82.213:16261:16261"
      - "69.162.82.213:16261:16261/udp"
      - "69.162.82.213:16262-16286:16262-16286"
    networks:
      - pz-network
      - game-network

  l4d2:
    ports:
      - "69.162.82.212:27015:27015/udp"
    networks:
      - l4d2-network
      - game-network
  
  valheim:
    ports:
      - "69.162.82.213:2456-2458:2456-2458"
      - "69.162.82.213:2456-2458:2456-2458/udp"
    networks:
      - tf2-network
      - game-network
  
  palworld:
    ports:
      - 69.162.82.213:8211:8211/udp
      - 69.162.82.213:27015:27015/udp
    networks:
      - palworld-network
      - game-network
  
  fastdownload:
    ports:
      - "69.162.82.212:38929:80"

  cache:
    networks:
      game-network:
        ipv4_address: 172.28.0.1
      external:
  dns:
    networks:
      game-network:
        ipv4_address: 172.28.0.2
      external:
  
networks:
  tf2-network:
    driver_opts:
      com.docker.network.bridge.name: bridge-tf2
      com.docker.network.bridge.enable_ip_masquerade: "false"
    ipam:
      config:
      - subnet: 10.1.0.0/16
        ip_range: 10.1.1.0/24

  css-network:
    driver_opts:
      com.docker.network.bridge.name: bridge-css
      com.docker.network.bridge.enable_ip_masquerade: "false"
    ipam:
      config:
      - subnet: 10.2.0.0/16
        ip_range: 10.2.1.0/24

  pz-network:
    driver_opts:
      com.docker.network.bridge.name: bridge-pz
      com.docker.network.bridge.enable_ip_masquerade: "false"
    ipam:
      config:
      - subnet: 10.3.0.0/16
        ip_range: 10.3.1.0/24

  l4d2-network:
    driver_opts:
      com.docker.network.bridge.name: bridge-l4d2
      com.docker.network.bridge.enable_ip_masquerade: "false"
    ipam:
      config:
      - subnet: 10.4.0.0/16
        ip_range: 10.4.1.0/24
  
  palworld-network:
    driver_opts:
      com.docker.network.bridge.name: bridge-palworld
      com.docker.network.bridge.enable_ip_masquerade: "false"
    ipam:
      config:
      - subnet: 10.5.0.0/16
        ip_range: 10.5.1.0/24

  game-network:
    internal: true
    ipam:
      config:
      - subnet: 172.28.0.0/16
        ip_range: 172.28.5.0/24
  external:
    internal: false
